// <auto-generated />
using System;
using Microservice2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservice2.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20201219053313_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Microservice2.Entities.CContext", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ceo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("listed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stockexc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cid");

                    b.ToTable("CContexts");
                });

            modelBuilder.Entity("Microservice2.Entities.IPOContext", b =>
                {
                    b.Property<int>("Iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockExchage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_shares")
                        .HasColumnType("int");

                    b.Property<DateTime>("open_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("price_per_share")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iid");

                    b.ToTable("IPOContexts");
                });

            modelBuilder.Entity("Microservice2.Entities.SPContext", b =>
                {
                    b.Property<int>("SPid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Ccode")
                        .HasColumnType("int");

                    b.Property<string>("SE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tstamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("SPid");

                    b.HasIndex("Ccode");

                    b.ToTable("SPContexts");
                });

            modelBuilder.Entity("Microservice2.Entities.SPContext", b =>
                {
                    b.HasOne("Microservice2.Entities.CContext", "Comp")
                        .WithMany()
                        .HasForeignKey("Ccode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comp");
                });
#pragma warning restore 612, 618
        }
    }
}
