// <auto-generated />
using Microservice5.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservice5.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20201210121713_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CContextSEContext", b =>
                {
                    b.Property<int>("Companycid")
                        .HasColumnType("int");

                    b.Property<int>("StockExchangesid")
                        .HasColumnType("int");

                    b.HasKey("Companycid", "StockExchangesid");

                    b.HasIndex("StockExchangesid");

                    b.ToTable("CContextSEContext");
                });

            modelBuilder.Entity("Microservice5.Entities.CContext", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cid");

                    b.ToTable("CContexts");
                });

            modelBuilder.Entity("Microservice5.Entities.SEContext", b =>
                {
                    b.Property<int>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sid");

                    b.ToTable("SEContexts");
                });

            modelBuilder.Entity("CContextSEContext", b =>
                {
                    b.HasOne("Microservice5.Entities.CContext", null)
                        .WithMany()
                        .HasForeignKey("Companycid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservice5.Entities.SEContext", null)
                        .WithMany()
                        .HasForeignKey("StockExchangesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
